//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKyWF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public int mstk { get; set; }
        public string ChucVu1 { get; set; }
    
        public virtual user_pass user_pass { get; set; }
    }
}
