//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKyWF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy
    {
        public int msMon { get; set; }
        public int msSinhVien { get; set; }
        public Nullable<System.DateTime> NgayKetThucMon { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
