//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKyWF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.DangKies = new HashSet<DangKy>();
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public string diaChi { get; set; }
        public string gioiTinh { get; set; }
        public Nullable<int> tuoi { get; set; }
        public string hoTen { get; set; }
        public Nullable<int> sdt { get; set; }
        public int mssv { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<int> msLop { get; set; }
        public Nullable<int> msKhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKy> DangKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
